// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package getchatsmock is a generated GoMock package.
package getchatsmock

import (
	context "context"
	reflect "reflect"

	chats "github.com/gerladeno/chat-service/internal/repositories/chats"
	types "github.com/gerladeno/chat-service/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockchatsRepo is a mock of chatsRepo interface.
type MockchatsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockchatsRepoMockRecorder
}

// MockchatsRepoMockRecorder is the mock recorder for MockchatsRepo.
type MockchatsRepoMockRecorder struct {
	mock *MockchatsRepo
}

// NewMockchatsRepo creates a new mock instance.
func NewMockchatsRepo(ctrl *gomock.Controller) *MockchatsRepo {
	mock := &MockchatsRepo{ctrl: ctrl}
	mock.recorder = &MockchatsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatsRepo) EXPECT() *MockchatsRepoMockRecorder {
	return m.recorder
}

// GetChatsForManager mocks base method.
func (m *MockchatsRepo) GetChatsForManager(ctx context.Context, managerID types.UserID) ([]chats.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatsForManager", ctx, managerID)
	ret0, _ := ret[0].([]chats.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatsForManager indicates an expected call of GetChatsForManager.
func (mr *MockchatsRepoMockRecorder) GetChatsForManager(ctx, managerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatsForManager", reflect.TypeOf((*MockchatsRepo)(nil).GetChatsForManager), ctx, managerID)
}
