// Code generated by options-gen. DO NOT EDIT.
package clientmessagesentjob

type OptOptionsSetter func(o *Options)

func NewOptions(
	messageRepository messageRepository,
	eventStream eventStream,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.messageRepository = messageRepository
	o.eventStream = eventStream

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}
