version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    profiles: [ "swagger-ui" ]
    ports:
      - "127.0.0.1:3011:8080"
    volumes:
      - ../../api:/api
    environment:
      SWAGGER_JSON: "/api/client.v1.swagger.yml"
      URLS: "[{url: 'client.v1.swagger.yml', name: 'client.v1.swagger'},
      {url: 'manager.v1.swagger.yml', name: 'manager.v1.swagger'},
      {url: 'client.events.swagger.yml', name: 'client.events.swagger'},
      {url: 'manager.events.swagger.yml', name: 'manager.events.swagger'}]"
