[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
sec_ws_protocol = "chat-service-protocol"
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[servers.manager]
addr = ":8081"
allow_origins = ["http://localhost:3011", "http://localhost:3001"]
sec_ws_protocol = "chat-service-protocol"
[servers.manager.required_access]
resource = "chat-ui-manager"
role = "support-chat-manager"

[sentry]
dsn = "http://11617821b1a2471a916c3fbc5bbd1163@localhost:9000/2"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "подставьте-свой-секрет"
debug_mode = false

[db]
[db.postgres]
user = "chat-service"
password = "chat-service"
addr = "localhost:5432"
database = "postgres"
debug_mode = true

[services]
[services.msg_producer]
brokers = ["localhost:9092"]
topic = "chat.messages"
batch_size = 1
encrypt_key = "" # Leave it blank to disable encryption.

[services.outbox]
workers = 2
idle_time = "1s"
reserve_for = "5m"

[services.manager_load]
max_problems_at_same_time = 5