// Code generated by options-gen. DO NOT EDIT.
package sendmanagermessagejob

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	chatsRepository chatsRepository,
	messageRepository messageRepository,
	eventStream eventStream,
	messageProducer messageProducer,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.chatsRepository = chatsRepository
	o.messageRepository = messageRepository
	o.eventStream = eventStream
	o.messageProducer = messageProducer

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("chatsRepository", _validate_Options_chatsRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("messageRepository", _validate_Options_messageRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventStream", _validate_Options_eventStream(o)))
	errs.Add(errors461e464ebed9.NewValidationError("messageProducer", _validate_Options_messageProducer(o)))
	return errs.AsError()
}

func _validate_Options_chatsRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.chatsRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `chatsRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_messageRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.messageRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `messageRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventStream(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventStream, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventStream` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_messageProducer(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.messageProducer, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `messageProducer` did not pass the test: %w", err)
	}
	return nil
}
