// Package managerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package managerevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/gerladeno/chat-service/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
)

// Event defines model for Event.
type Event struct {
	EventId   types.EventID   `json:"eventId"`
	EventType string          `json:"eventType"`
	RequestId types.RequestID `json:"requestId"`
	union     json.RawMessage
}

// Message defines model for Message.
type Message struct {
	AuthorId  types.UserID    `json:"authorId"`
	Body      string          `json:"body"`
	CreatedAt time.Time       `json:"createdAt"`
	MessageId types.MessageID `json:"messageId"`
}

// MessageId defines model for MessageId.
type MessageId struct {
	MessageId types.MessageID `json:"messageId"`
}

// MessageSentEvent defines model for MessageSentEvent.
type MessageSentEvent = MessageId

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	CanTakeMoreProblems bool         `json:"canTakeMoreProblems"`
	ChatId              types.ChatID `json:"chatId"`
	ClientId            types.UserID `json:"clientId"`
}

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent = Message

// AsNewMessageEvent returns the union data inside the Event as a NewMessageEvent
func (t Event) AsNewMessageEvent() (NewMessageEvent, error) {
	var body NewMessageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewMessageEvent overwrites any union data inside the Event as the provided NewMessageEvent
func (t *Event) FromNewMessageEvent(v NewMessageEvent) error {
	t.EventType = "NewMessageEvent"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewMessageEvent performs a merge with any union data inside the Event, using the provided NewMessageEvent
func (t *Event) MergeNewMessageEvent(v NewMessageEvent) error {
	t.EventType = "NewMessageEvent"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

// AsMessageSentEvent returns the union data inside the Event as a MessageSentEvent
func (t Event) AsMessageSentEvent() (MessageSentEvent, error) {
	var body MessageSentEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageSentEvent overwrites any union data inside the Event as the provided MessageSentEvent
func (t *Event) FromMessageSentEvent(v MessageSentEvent) error {
	t.EventType = "MessageSentEvent"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageSentEvent performs a merge with any union data inside the Event, using the provided MessageSentEvent
func (t *Event) MergeMessageSentEvent(v MessageSentEvent) error {
	t.EventType = "MessageSentEvent"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

// AsNewChatEvent returns the union data inside the Event as a NewChatEvent
func (t Event) AsNewChatEvent() (NewChatEvent, error) {
	var body NewChatEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewChatEvent overwrites any union data inside the Event as the provided NewChatEvent
func (t *Event) FromNewChatEvent(v NewChatEvent) error {
	t.EventType = "NewChatEvent"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewChatEvent performs a merge with any union data inside the Event, using the provided NewChatEvent
func (t *Event) MergeNewChatEvent(v NewChatEvent) error {
	t.EventType = "NewChatEvent"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"eventType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "MessageSentEvent":
		return t.AsMessageSentEvent()
	case "NewChatEvent":
		return t.AsNewChatEvent()
	case "NewMessageEvent":
		return t.AsNewMessageEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["eventId"], err = json.Marshal(t.EventId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'eventId': %w", err)
	}

	object["eventType"], err = json.Marshal(t.EventType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'eventType': %w", err)
	}

	object["requestId"], err = json.Marshal(t.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'requestId': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["eventId"]; found {
		err = json.Unmarshal(raw, &t.EventId)
		if err != nil {
			return fmt.Errorf("error reading 'eventId': %w", err)
		}
	}

	if raw, found := object["eventType"]; found {
		err = json.Unmarshal(raw, &t.EventType)
		if err != nil {
			return fmt.Errorf("error reading 'eventType': %w", err)
		}
	}

	if raw, found := object["requestId"]; found {
		err = json.Unmarshal(raw, &t.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'requestId': %w", err)
		}
	}

	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWS28aMRD+K2jao2ET9RL51pYeOCStmvQU5TB4h103ftX2QhHa/17ZbGAXojykVEJV",
	"b5Y98+l7DMNuQFjtrCETA/ANBFGTxnz8siQT06GUQXippcFofbrQ6Jw0VTpeUghY0TWZ2NXDu2IPWXR4",
	"xVEdgytafa7x6bZBTW7pgJ7rGpS1DJy3jnxcX6Em4EDp/mbtKL1ZQ18XwG838N7T4uWgT9cfKX6uYaC1",
	"vdtxlpTjyJRnZTourNeY1DeNLIFBTEI4hOhTKgx+jys7ltpZn/NzGGvgUMlYN/OJsLqoyCssydhC1BjH",
	"gfxSCiqkieQNqiIBhmRNRurg8+Uk05tN0+PeRL454NAy8PSroXACjL93RKbQdrSkpxL4bU8A29nbJ37X",
	"socBT6xQqRfMSdcwK3PgwwyxibX1r7BkIORHID+b9p/ewrKWwdyW60czFJ4wUvkxDgiXGGkcpaYj1ocG",
	"Z+A+DNtbcLdrtvOfJNLI7+3eWjQ0T/efXu/eA/LbG3gges+zJ6i3IP8NXcPtfahJoLnBe7q0nr55O1ek",
	"Q2/A5tYqQpMnrMYTWBFJyXanCSVPYs12v/XDDDq7ejzZo153CQ3/LP9vsL+/wVK/NAubycio0usnNPej",
	"68YloaM0aqNLNFiRH+VgAjBYkg/SGuCwPM+fJI4MOgkcPkzOJ2fAsjsBuGmUYpCcIB9ykiWlrzMXt+1T",
	"WpKyTpOJo20VMGi8Ag6rwItCWYGqtiHyi7OL82IVEuk/AQAA//+Gbl2yBQoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
