// Code generated by options-gen. DO NOT EDIT.
package closechat

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	msgRepo msgRepo,
	problemsRepo problemsRepo,
	outboxService outboxService,
	transactor transactor,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.msgRepo = msgRepo
	o.problemsRepo = problemsRepo
	o.outboxService = outboxService
	o.transactor = transactor

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("msgRepo", _validate_Options_msgRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("problemsRepo", _validate_Options_problemsRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("outboxService", _validate_Options_outboxService(o)))
	errs.Add(errors461e464ebed9.NewValidationError("transactor", _validate_Options_transactor(o)))
	return errs.AsError()
}

func _validate_Options_msgRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.msgRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `msgRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_problemsRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.problemsRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `problemsRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_outboxService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.outboxService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `outboxService` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_transactor(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.transactor, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `transactor` did not pass the test: %w", err)
	}
	return nil
}
